import type { Translations } from './es'

const ar: Translations = {
  app: { name: 'Codebase Insight Lab', openFolder: 'فتح مجلد', addFolder: 'إضافة مجلد', recentProjects: 'المشاريع الأخيرة', saveSession: 'حفظ الجلسة', newSession: 'جلسة جديدة', settings: 'الإعدادات', language: 'اللغة', noWorkspace: 'لا توجد مساحة عمل', openToStart: 'افتح مجلداً للبدء' },
  explorer: { title: 'المستكشف', noFolder: 'لا يوجد مجلد مفتوح', noFolderDesc: 'افتح مجلداً لاستعراض الملفات', addFolder: '+ إضافة مجلد', loading: 'جارٍ التحميل...' },
  editor: { noFileOpen: 'لا يوجد ملف مفتوح', noFileDesc: 'اختر ملفاً من المستكشف', analyzeBtn: '⚡ تحليل مع العملاء', analyzingHint: 'جارٍ التحليل...', line: 'سطر', col: 'عمود' },
  ai: { analysis: 'التحليل', coder: 'المبرمج', summary: 'الملخص', analysisTitle: 'تحليل الذكاء الاصطناعي', coderTitle: 'مبرمج الذكاء الاصطناعي', summaryTitle: 'ملخص الذكاء الاصطناعي', noResponses: 'لا توجد ردود', noResponsesDesc: 'افتح ملفاً وانقر ⚡ تحليل', analyzing: 'العملاء يحللون...', clearResponses: 'مسح الردود', askPlaceholder: 'اسأل عن الكود...', send: 'إرسال', askNext: 'السؤال التالي', depth: 'العمق', depthSummary: 'ملخص', depthTechnical: 'تقني', depthComplete: 'شامل', depthEli5: 'شرح مبسط', depthSenior: 'مطور أقدم', coderTaskPlaceholder: 'صف مهمة البرمجة...', coderGenerate: 'توليد التغييرات', coderGenerating: 'جارٍ التوليد...', coderAcceptAll: 'قبول الكل', coderRejectAll: 'رفض الكل', coderNoPending: 'لا توجد تغييرات معلقة', coderNoPendingDesc: 'صف مهمة', coderAccept: 'قبول', coderReject: 'رفض', coderExplain: 'شرح', summaryGenerate: 'توليد وثيقة', summaryGenerating: 'جارٍ التوليد...', summaryNoDoc: 'لا توجد وثيقة', summaryNoDocDesc: 'توليد تحليل شامل', summaryEdit: 'تعديل', summarySave: 'حفظ', summaryExport: 'تصدير', modelSelector: 'اختر النموذج', agents: 'العملاء', connected: 'Cortex متصل', disconnected: 'Cortex غير متصل', conversationHistory: 'سجل المحادثات', newConversation: 'محادثة جديدة', loadConversation: 'تحميل محادثة', deleteResponse: 'حذف الرد', responseInterrupted: 'مقطوع', responseInterruptedTitle: 'انقطع الاتصال. هذا الرد غير مكتمل.' },
  depth: { summary: 'ملخص موجز', technical: 'شرح تقني مفصل', complete: 'تحليل شامل', eli5: 'شرح مبسط', senior: 'كمطور أقدم' },
  terminal: { title: 'الطرفية', newTerminal: 'طرفية جديدة', closeTerminal: 'إغلاق الطرفية', clear: 'مسح', renameTerminal: 'إعادة تسمية', placeholder: 'أدخل أمراً...', running: 'جارٍ التنفيذ...', exitCode: 'رمز الخروج' },
  diff: { proposed: 'التغييرات المقترحة', original: 'الأصلي', modified: 'المعدّل', accept: 'قبول', reject: 'رفض', explain: 'شرح التغيير', change: 'تغيير', changes: 'تغييرات', acceptAll: 'قبول الكل', rejectAll: 'رفض الكل', noChanges: 'لا توجد تغييرات', applied: 'تم تطبيق التغيير', rejected: 'تم رفض التغيير' },
  status: { terminal: 'الطرفية', ln: 'سطر', col: 'عمود' },
  session: { saved: 'تم حفظ الجلسة', loaded: 'تم تحميل الجلسة', noRecent: 'لا توجد مشاريع أخيرة', saveProject: 'حفظ المشروع', loadProject: 'تحميل المشروع', projectName: 'اسم المشروع', lastOpened: 'آخر فتح', conversations: 'محادثات', resumeSession: 'استئناف الجلسة', newSession: 'جلسة جديدة', restore: 'استعادة الجلسة الأخيرة', restoreProject: 'استئناف المشروع', restored: 'تم استعادة الجلسة', saving: 'جارٍ الحفظ...', clickToRestore: 'انقر لإعادة الفتح' },
  run: { title: 'تشغيل المشروع', command: 'الأمر', omit: 'استثناء الملفات/المجلدات', omitHint: 'أنماط مفصولة بفاصلة (مثال: .env,tests/)', contextPrompt: 'السياق (اختياري)', contextHint: 'سياق إضافي لوكلاء الذكاء الاصطناعي', execute: 'تشغيل', skip: 'تخطي', running: 'جارٍ التشغيل...', analyzing: 'تحليل الأخطاء...', noCommand: 'لم يتم اكتشاف أمر تشغيل', errorFound: 'تم اكتشاف أخطاء', runBtn: '▶ تشغيل', runningBtn: '⏳ جارٍ التشغيل...', analyzeProject: '🔍 تحليل المشروع', analyzingProject: 'جارٍ التحليل...', lastRun: 'آخر نتيجة' },
  config: { title: 'إعداد المشروع', created: 'تم إنشاء دليل الإعداد', gitignoreUpdated: 'تم تحديث .gitignore', configDir: 'دليل الإعداد', save: 'حفظ التغييرات', confirmEdit: 'تأكيد التغييرات' },
}
export default ar
