import type { Translations } from './es'

const de: Translations = {
  app: { name: 'Codebase Insight Lab', openFolder: 'Ordner öffnen', addFolder: 'Ordner hinzufügen', recentProjects: 'Zuletzt geöffnete Projekte', saveSession: 'Sitzung speichern', newSession: 'Neue Sitzung', settings: 'Einstellungen', language: 'Sprache', noWorkspace: 'Kein Workspace', openToStart: 'Öffne einen Ordner, um zu beginnen' },
  explorer: { title: 'Explorer', noFolder: 'Kein Ordner geöffnet', noFolderDesc: 'Öffne einen Ordner, um Dateien zu durchsuchen', addFolder: '+ Ordner hinzufügen', removeFolder: 'Ordner entfernen', loading: 'Laden...' },
  editor: { noFileOpen: 'Keine Datei geöffnet', noFileDesc: 'Wähle eine Datei aus dem Explorer', analyzeBtn: '⚡ Mit Agenten analysieren', analyzingHint: 'Analysiere...', line: 'Zeile', col: 'Sp' },
  ai: { analysis: 'Analyse', coder: 'Programmierer', summary: 'Zusammenfassung', analysisTitle: 'KI-Analyse', coderTitle: 'KI-Programmierer', summaryTitle: 'KI-Zusammenfassung', noResponses: 'Noch keine Antworten', noResponsesDesc: 'Öffne eine Datei und klicke ⚡ Analysieren', analyzing: 'Agenten analysieren...', clearResponses: 'Antworten löschen', askPlaceholder: 'Frage zum Code...', send: 'Senden', askNext: 'Als nächstes fragen', depth: 'Tiefe', depthSummary: 'Zusammenfassung', depthTechnical: 'Technisch', depthComplete: 'Vollständig', depthEli5: 'Einfach erklärt', depthSenior: 'Senior Dev', coderTaskPlaceholder: 'Beschreibe die Aufgabe...', coderGenerate: 'Änderungen generieren', coderGenerating: 'Generiere...', coderAcceptAll: 'Alle akzeptieren', coderRejectAll: 'Alle ablehnen', coderNoPending: 'Keine ausstehenden Änderungen', coderNoPendingDesc: 'Beschreibe eine Aufgabe', coderAccept: 'Akzeptieren', coderReject: 'Ablehnen', coderExplain: 'Erklären', summaryGenerate: 'Dokument generieren', summaryGenerating: 'Generiere...', summaryNoDoc: 'Kein Dokument generiert', summaryNoDocDesc: 'Vollständige Repository-Analyse generieren', summaryEdit: 'Bearbeiten', summarySave: 'Speichern', summaryExport: 'Exportieren', modelSelector: 'Modell auswählen', agents: 'Agenten', connected: 'Cortex verbunden', disconnected: 'Cortex getrennt', conversationHistory: 'Gesprächsverlauf', newConversation: 'Neues Gespräch', loadConversation: 'Gespräch laden', deleteResponse: 'Antwort löschen', responseInterrupted: 'Unterbrochen', responseInterruptedTitle: 'Die Verbindung wurde unterbrochen. Diese Antwort ist unvollständig.' },
  depth: { summary: 'Kurze Übersicht', technical: 'Technische Erklärung', complete: 'Erschöpfende Analyse', eli5: 'Einfach erklärt', senior: 'Wie mit einem Senior Dev' },
  terminal: { title: 'Terminal', newTerminal: 'Neues Terminal', closeTerminal: 'Terminal schließen', clear: 'Leeren', renameTerminal: 'Umbenennen', placeholder: 'Befehl eingeben...', running: 'Läuft...', exitCode: 'Exit-Code' },
  diff: { proposed: 'Vorgeschlagene Änderungen', original: 'Original', modified: 'Geändert', accept: 'Akzeptieren', reject: 'Ablehnen', explain: 'Änderung erklären', change: 'Änderung', changes: 'Änderungen', acceptAll: 'Alle akzeptieren', rejectAll: 'Alle ablehnen', noChanges: 'Keine Änderungen', applied: 'Änderung angewendet', rejected: 'Änderung abgelehnt' },
  status: { terminal: 'Terminal', ln: 'Zl', col: 'Sp' },
  session: { saved: 'Sitzung gespeichert', loaded: 'Sitzung geladen', noRecent: 'Keine aktuellen Projekte', saveProject: 'Projekt speichern', loadProject: 'Projekt laden', projectName: 'Projektname', lastOpened: 'Zuletzt geöffnet', conversations: 'Gespräche', resumeSession: 'Sitzung fortsetzen', newSession: 'Neue Sitzung', restore: 'Letzte Sitzung wiederherstellen', restoreProject: 'Projekt fortsetzen', restored: 'Sitzung wiederhergestellt', saving: 'Sitzung speichern...', clickToRestore: 'Klicken zum Öffnen' },
  run: { title: 'Projekt ausführen', command: 'Befehl', omit: 'Dateien/Ordner auslassen', omitHint: 'Kommagetrennte Muster (z.B. .env,tests/)', contextPrompt: 'Kontext (optional)', contextHint: 'Zusätzlicher Kontext für KI-Agenten', execute: 'Ausführen', skip: 'Überspringen', running: 'Läuft...', analyzing: 'Fehler werden analysiert...', noCommand: 'Kein Befehl erkannt', errorFound: 'Fehler erkannt', runBtn: '▶ Ausführen', runningBtn: '⏳ Läuft...', analyzeProject: '🔍 Projekt analysieren', analyzingProject: 'Analysiere...', lastRun: 'Letzter Lauf' },
  config: { title: 'Projektkonfiguration', created: 'Konfigurationsverzeichnis erstellt', gitignoreUpdated: '.gitignore aktualisiert', configDir: 'Konfig-Verzeichnis', save: 'Änderungen speichern', confirmEdit: 'Änderungen bestätigen' },
}
export default de
