import type { Translations } from './es'

const fr: Translations = {
  app: { name: 'Codebase Insight Lab', openFolder: 'Ouvrir dossier', addFolder: 'Ajouter dossier', recentProjects: 'Projets récents', saveSession: 'Sauvegarder session', newSession: 'Nouvelle session', settings: 'Paramètres', language: 'Langue', noWorkspace: 'Aucun workspace', openToStart: 'Ouvrez un dossier pour commencer' },
  explorer: { title: 'Explorateur', noFolder: 'Aucun dossier ouvert', noFolderDesc: 'Ouvrez un dossier pour parcourir ses fichiers', addFolder: '+ Ajouter dossier', loading: 'Chargement...' },
  editor: { noFileOpen: 'Aucun fichier ouvert', noFileDesc: 'Sélectionnez un fichier dans l\'explorateur', analyzeBtn: '⚡ Analyser avec les agents', analyzingHint: 'Analyse...', line: 'Ligne', col: 'Col' },
  ai: { analysis: 'Analyse', coder: 'Codeur', summary: 'Résumé', analysisTitle: 'IA Analyse', coderTitle: 'IA Codeur', summaryTitle: 'IA Résumé', noResponses: 'Aucune réponse', noResponsesDesc: 'Ouvrez un fichier et cliquez ⚡ Analyser', analyzing: 'Agents en analyse...', clearResponses: 'Effacer réponses', askPlaceholder: 'Posez une question sur le code...', send: 'Envoyer', askNext: 'Demander ensuite', depth: 'Profondeur', depthSummary: 'Résumé', depthTechnical: 'Technique', depthComplete: 'Complet', depthEli5: 'Explication simple', depthSenior: 'Senior Dev', coderTaskPlaceholder: 'Décrivez la tâche de code...', coderGenerate: 'Générer changements', coderGenerating: 'Génération...', coderAcceptAll: 'Tout accepter', coderRejectAll: 'Tout rejeter', coderNoPending: 'Aucun changement en attente', coderNoPendingDesc: 'Décrivez une tâche', coderAccept: 'Accepter', coderReject: 'Rejeter', coderExplain: 'Expliquer', summaryGenerate: 'Générer document', summaryGenerating: 'Génération...', summaryNoDoc: 'Aucun document', summaryNoDocDesc: 'Générez une analyse complète', summaryEdit: 'Modifier', summarySave: 'Sauvegarder', summaryExport: 'Exporter', modelSelector: 'Sélectionner modèle', agents: 'Agents', connected: 'Cortex connecté', disconnected: 'Cortex déconnecté', conversationHistory: 'Historique', newConversation: 'Nouvelle conversation', loadConversation: 'Charger conversation', deleteResponse: 'Supprimer la réponse', responseInterrupted: 'Interrompue', responseInterruptedTitle: 'La connexion a été interrompue. Cette réponse est incomplète.' },
  depth: { summary: 'Réponse brève', technical: 'Explication technique', complete: 'Analyse exhaustive', eli5: 'Explication simple', senior: 'Comme un développeur senior' },
  terminal: { title: 'Terminal', newTerminal: 'Nouveau terminal', closeTerminal: 'Fermer terminal', clear: 'Effacer', renameTerminal: 'Renommer', placeholder: 'Entrez une commande...', running: 'En cours...', exitCode: 'Code de sortie' },
  diff: { proposed: 'Changements proposés', original: 'Original', modified: 'Modifié', accept: 'Accepter', reject: 'Rejeter', explain: 'Expliquer', change: 'changement', changes: 'changements', acceptAll: 'Tout accepter', rejectAll: 'Tout rejeter', noChanges: 'Aucun changement', applied: 'Changement appliqué', rejected: 'Changement rejeté' },
  status: { terminal: 'Terminal', ln: 'Ln', col: 'Col' },
  session: { saved: 'Session sauvegardée', loaded: 'Session chargée', noRecent: 'Aucun projet récent', saveProject: 'Sauvegarder projet', loadProject: 'Charger projet', projectName: 'Nom du projet', lastOpened: 'Dernière ouverture', conversations: 'conversations', resumeSession: 'Reprendre session', newSession: 'Nouvelle session', restore: 'Restaurer la dernière session', restoreProject: 'Reprendre le projet', restored: 'Session restaurée', saving: 'Sauvegarde en cours...', clickToRestore: 'Cliquer pour rouvrir' },
  run: { title: 'Exécuter le projet', command: 'Commande', omit: 'Omettre fichiers/dossiers', omitHint: 'Modèles séparés par virgule (ex: .env,tests/)', contextPrompt: 'Contexte (optionnel)', contextHint: 'Contexte pour les agents IA', execute: 'Exécuter', skip: 'Ignorer', running: 'En cours...', analyzing: 'Analyse des erreurs...', noCommand: 'Aucune commande détectée', errorFound: 'Erreurs détectées', runBtn: '▶ Exécuter', runningBtn: '⏳ En cours...', analyzeProject: '🔍 Analyser le projet', analyzingProject: 'Analyse...', lastRun: 'Dernier résultat' },
  config: { title: 'Configuration du projet', created: 'Config créée', gitignoreUpdated: '.gitignore mis à jour', configDir: 'Répertoire de config', save: 'Sauvegarder', confirmEdit: 'Confirmer les modifications' },
}
export default fr
