import type { Translations } from './es'

const it: Translations = {
  app: { name: 'Codebase Insight Lab', openFolder: 'Apri cartella', addFolder: 'Aggiungi cartella', recentProjects: 'Progetti recenti', saveSession: 'Salva sessione', newSession: 'Nuova sessione', settings: 'Impostazioni', language: 'Lingua', noWorkspace: 'Nessun workspace', openToStart: 'Apri una cartella per iniziare' },
  explorer: { title: 'Esplora', noFolder: 'Nessuna cartella aperta', noFolderDesc: 'Apri una cartella per sfogliare i file', addFolder: '+ Aggiungi cartella', loading: 'Caricamento...' },
  editor: { noFileOpen: 'Nessun file aperto', noFileDesc: 'Seleziona un file dall\'esploratore', analyzeBtn: '⚡ Analizza con gli agenti', analyzingHint: 'Analisi...', line: 'Riga', col: 'Col' },
  ai: { analysis: 'Analisi', coder: 'Programmatore', summary: 'Riepilogo', analysisTitle: 'IA Analisi', coderTitle: 'IA Programmatore', summaryTitle: 'IA Riepilogo', noResponses: 'Nessuna risposta', noResponsesDesc: 'Apri un file e clicca ⚡ Analizza', analyzing: 'Agenti in analisi...', clearResponses: 'Cancella risposte', askPlaceholder: 'Fai una domanda sul codice...', send: 'Invia', askNext: 'Chiedi dopo', depth: 'Profondità', depthSummary: 'Riepilogo', depthTechnical: 'Tecnico', depthComplete: 'Completo', depthEli5: 'Spiegazione semplice', depthSenior: 'Senior Dev', coderTaskPlaceholder: 'Descrivi il compito di codifica...', coderGenerate: 'Genera modifiche', coderGenerating: 'Generazione...', coderAcceptAll: 'Accetta tutto', coderRejectAll: 'Rifiuta tutto', coderNoPending: 'Nessuna modifica in sospeso', coderNoPendingDesc: 'Descrivi un compito', coderAccept: 'Accetta', coderReject: 'Rifiuta', coderExplain: 'Spiega', summaryGenerate: 'Genera documento', summaryGenerating: 'Generazione...', summaryNoDoc: 'Nessun documento', summaryNoDocDesc: 'Genera un\'analisi completa', summaryEdit: 'Modifica', summarySave: 'Salva', summaryExport: 'Esporta', modelSelector: 'Seleziona modello', agents: 'Agenti', connected: 'Cortex connesso', disconnected: 'Cortex disconnesso', conversationHistory: 'Cronologia', newConversation: 'Nuova conversazione', loadConversation: 'Carica conversazione', deleteResponse: 'Elimina risposta', responseInterrupted: 'Interrotta', responseInterruptedTitle: 'La connessione è stata interrotta. Questa risposta è incompleta.' },
  depth: { summary: 'Risposta breve', technical: 'Spiegazione tecnica', complete: 'Analisi esaustiva', eli5: 'Spiegazione semplice', senior: 'Come un senior developer' },
  terminal: { title: 'Terminale', newTerminal: 'Nuovo terminale', closeTerminal: 'Chiudi terminale', clear: 'Pulisci', renameTerminal: 'Rinomina', placeholder: 'Inserisci un comando...', running: 'In esecuzione...', exitCode: 'Codice di uscita' },
  diff: { proposed: 'Modifiche proposte', original: 'Originale', modified: 'Modificato', accept: 'Accetta', reject: 'Rifiuta', explain: 'Spiega modifica', change: 'modifica', changes: 'modifiche', acceptAll: 'Accetta tutto', rejectAll: 'Rifiuta tutto', noChanges: 'Nessuna modifica', applied: 'Modifica applicata', rejected: 'Modifica rifiutata' },
  status: { terminal: 'Terminale', ln: 'Rg', col: 'Col' },
  session: { saved: 'Sessione salvata', loaded: 'Sessione caricata', noRecent: 'Nessun progetto recente', saveProject: 'Salva progetto', loadProject: 'Carica progetto', projectName: 'Nome progetto', lastOpened: 'Ultima apertura', conversations: 'conversazioni', resumeSession: 'Riprendi sessione', newSession: 'Nuova sessione', restore: 'Ripristina ultima sessione', restoreProject: 'Riprendi progetto', restored: 'Sessione ripristinata', saving: 'Salvataggio...', clickToRestore: 'Clicca per riaprire' },
  run: { title: 'Esegui progetto', command: 'Comando', omit: 'Ometti file/cartelle', omitHint: 'Pattern separati da virgola (es: .env,tests/)', contextPrompt: 'Contesto (opzionale)', contextHint: 'Contesto per gli agenti IA', execute: 'Esegui', skip: 'Salta', running: 'In esecuzione...', analyzing: 'Analisi errori...', noCommand: 'Nessun comando rilevato', errorFound: 'Errori rilevati', runBtn: '▶ Esegui', runningBtn: '⏳ In esecuzione...', analyzeProject: '🔍 Analizza progetto', analyzingProject: 'Analisi...', lastRun: 'Ultimo risultato' },
  config: { title: 'Configurazione progetto', created: 'Config creata', gitignoreUpdated: '.gitignore aggiornato', configDir: 'Directory di config', save: 'Salva modifiche', confirmEdit: 'Conferma modifiche' },
}
export default it
