import type { Translations } from './es'

const pt: Translations = {
  app: { name: 'Codebase Insight Lab', openFolder: 'Abrir pasta', addFolder: 'Adicionar pasta', recentProjects: 'Projetos recentes', saveSession: 'Salvar sessão', newSession: 'Nova sessão', settings: 'Configurações', language: 'Idioma', noWorkspace: 'Sem workspace', openToStart: 'Abra uma pasta para começar' },
  explorer: { title: 'Explorador', noFolder: 'Nenhuma pasta aberta', noFolderDesc: 'Abra uma pasta para navegar pelos arquivos', addFolder: '+ Adicionar pasta', removeFolder: 'Remover pasta', loading: 'Carregando...' },
  editor: { noFileOpen: 'Nenhum arquivo aberto', noFileDesc: 'Selecione um arquivo no explorador', analyzeBtn: '⚡ Analisar com agentes', analyzingHint: 'Analisando...', line: 'Linha', col: 'Col' },
  ai: { analysis: 'Análise', coder: 'Programador', summary: 'Resumo', analysisTitle: 'IA Análise', coderTitle: 'IA Programador', summaryTitle: 'IA Resumo', noResponses: 'Nenhuma resposta', noResponsesDesc: 'Abra um arquivo e clique ⚡ Analisar', analyzing: 'Agentes analisando...', clearResponses: 'Limpar respostas', askPlaceholder: 'Faça uma pergunta sobre o código...', send: 'Enviar', askNext: 'Perguntar em seguida', depth: 'Profundidade', depthSummary: 'Resumo', depthTechnical: 'Técnico', depthComplete: 'Completo', depthEli5: 'Explicação simples', depthSenior: 'Senior Dev', coderTaskPlaceholder: 'Descreva a tarefa de código...', coderGenerate: 'Gerar alterações', coderGenerating: 'Gerando...', coderAcceptAll: 'Aceitar tudo', coderRejectAll: 'Rejeitar tudo', coderNoPending: 'Nenhuma alteração pendente', coderNoPendingDesc: 'Descreva uma tarefa', coderAccept: 'Aceitar', coderReject: 'Rejeitar', coderExplain: 'Explicar', summaryGenerate: 'Gerar documento', summaryGenerating: 'Gerando...', summaryNoDoc: 'Nenhum documento', summaryNoDocDesc: 'Gere uma análise completa', summaryEdit: 'Editar', summarySave: 'Salvar', summaryExport: 'Exportar', modelSelector: 'Selecionar modelo', agents: 'Agentes', connected: 'Cortex conectado', disconnected: 'Cortex desconectado', conversationHistory: 'Histórico', newConversation: 'Nova conversa', loadConversation: 'Carregar conversa', deleteResponse: 'Eliminar resposta', responseInterrupted: 'Interrompida', responseInterruptedTitle: 'A conexão foi interrompida. Esta resposta está incompleta.' },
  depth: { summary: 'Resposta breve', technical: 'Explicação técnica', complete: 'Análise exaustiva', eli5: 'Explicação simples', senior: 'Como um desenvolvedor sênior' },
  terminal: { title: 'Terminal', newTerminal: 'Novo terminal', closeTerminal: 'Fechar terminal', clear: 'Limpar', renameTerminal: 'Renomear', placeholder: 'Digite um comando...', running: 'Executando...', exitCode: 'Código de saída' },
  diff: { proposed: 'Alterações propostas', original: 'Original', modified: 'Modificado', accept: 'Aceitar', reject: 'Rejeitar', explain: 'Explicar alteração', change: 'alteração', changes: 'alterações', acceptAll: 'Aceitar tudo', rejectAll: 'Rejeitar tudo', noChanges: 'Nenhuma alteração', applied: 'Alteração aplicada', rejected: 'Alteração rejeitada' },
  status: { terminal: 'Terminal', ln: 'Ln', col: 'Col' },
  session: { saved: 'Sessão salva', loaded: 'Sessão carregada', noRecent: 'Nenhum projeto recente', saveProject: 'Salvar projeto', loadProject: 'Carregar projeto', projectName: 'Nome do projeto', lastOpened: 'Última abertura', conversations: 'conversas', resumeSession: 'Retomar sessão', newSession: 'Nova sessão', restore: 'Restaurar última sessão', restoreProject: 'Retomar projeto', restored: 'Sessão restaurada', saving: 'Salvando sessão...', clickToRestore: 'Clique para reabrir' },
  run: { title: 'Executar projeto', command: 'Comando', omit: 'Omitir arquivos/pastas', omitHint: 'Padrões separados por vírgula (ex: .env,tests/)', contextPrompt: 'Contexto (opcional)', contextHint: 'Contexto para agentes IA', execute: 'Executar', skip: 'Ignorar', running: 'Executando...', analyzing: 'Analisando erros...', noCommand: 'Nenhum comando detectado', errorFound: 'Erros detectados', runBtn: '▶ Executar', runningBtn: '⏳ Executando...', analyzeProject: '🔍 Analisar Projeto', analyzingProject: 'Analisando...', lastRun: 'Último resultado' },
  config: { title: 'Configuração do projeto', created: 'Config criada', gitignoreUpdated: '.gitignore atualizado', configDir: 'Diretório de config', save: 'Salvar alterações', confirmEdit: 'Confirmar alterações' },
}
export default pt
