import type { Translations } from './es'

const ru: Translations = {
  app: { name: 'Codebase Insight Lab', openFolder: 'Открыть папку', addFolder: 'Добавить папку', recentProjects: 'Последние проекты', saveSession: 'Сохранить сессию', newSession: 'Новая сессия', settings: 'Настройки', language: 'Язык', noWorkspace: 'Нет рабочей области', openToStart: 'Откройте папку для начала работы' },
  explorer: { title: 'Проводник', noFolder: 'Папка не открыта', noFolderDesc: 'Откройте папку для просмотра файлов', addFolder: '+ Добавить папку', removeFolder: 'Удалить папку', loading: 'Загрузка...' },
  editor: { noFileOpen: 'Файл не открыт', noFileDesc: 'Выберите файл в проводнике', analyzeBtn: '⚡ Анализировать с агентами', analyzingHint: 'Анализ...', line: 'Строка', col: 'Стб' },
  ai: { analysis: 'Анализ', coder: 'Программист', summary: 'Сводка', analysisTitle: 'ИИ Анализ', coderTitle: 'ИИ Программист', summaryTitle: 'ИИ Сводка', noResponses: 'Нет ответов', noResponsesDesc: 'Откройте файл и нажмите ⚡ Анализ', analyzing: 'Агенты анализируют...', clearResponses: 'Очистить ответы', askPlaceholder: 'Задайте вопрос о коде...', send: 'Отправить', askNext: 'Спросить далее', depth: 'Глубина', depthSummary: 'Сводка', depthTechnical: 'Технический', depthComplete: 'Полный', depthEli5: 'Простое объяснение', depthSenior: 'Senior Dev', coderTaskPlaceholder: 'Опишите задачу...', coderGenerate: 'Сгенерировать изменения', coderGenerating: 'Генерация...', coderAcceptAll: 'Принять все', coderRejectAll: 'Отклонить все', coderNoPending: 'Нет ожидающих изменений', coderNoPendingDesc: 'Опишите задачу', coderAccept: 'Принять', coderReject: 'Отклонить', coderExplain: 'Объяснить', summaryGenerate: 'Создать документ', summaryGenerating: 'Создание...', summaryNoDoc: 'Нет документа', summaryNoDocDesc: 'Создайте полный анализ', summaryEdit: 'Редактировать', summarySave: 'Сохранить', summaryExport: 'Экспорт', modelSelector: 'Выбрать модель', agents: 'Агенты', connected: 'Cortex подключён', disconnected: 'Cortex отключён', conversationHistory: 'История', newConversation: 'Новый разговор', loadConversation: 'Загрузить разговор', deleteResponse: 'Удалить ответ', responseInterrupted: 'Прервано', responseInterruptedTitle: 'Соединение было прервано. Ответ неполный.' },
  depth: { summary: 'Краткий обзор', technical: 'Подробное техническое объяснение', complete: 'Исчерпывающий анализ', eli5: 'Простое объяснение', senior: 'Как с опытным разработчиком' },
  terminal: { title: 'Терминал', newTerminal: 'Новый терминал', closeTerminal: 'Закрыть терминал', clear: 'Очистить', renameTerminal: 'Переименовать', placeholder: 'Введите команду...', running: 'Выполнение...', exitCode: 'Код выхода' },
  diff: { proposed: 'Предлагаемые изменения', original: 'Исходный', modified: 'Изменённый', accept: 'Принять', reject: 'Отклонить', explain: 'Объяснить изменение', change: 'изменение', changes: 'изменений', acceptAll: 'Принять все', rejectAll: 'Отклонить все', noChanges: 'Нет изменений', applied: 'Изменение применено', rejected: 'Изменение отклонено' },
  status: { terminal: 'Терминал', ln: 'Стр', col: 'Стб' },
  session: { saved: 'Сессия сохранена', loaded: 'Сессия загружена', noRecent: 'Нет последних проектов', saveProject: 'Сохранить проект', loadProject: 'Загрузить проект', projectName: 'Название проекта', lastOpened: 'Последнее открытие', conversations: 'разговоров', resumeSession: 'Продолжить сессию', newSession: 'Новая сессия', restore: 'Восстановить последнюю сессию', restoreProject: 'Продолжить проект', restored: 'Сессия восстановлена', saving: 'Сохранение...', clickToRestore: 'Нажмите, чтобы открыть' },
  run: { title: 'Запустить проект', command: 'Команда', omit: 'Исключить файлы/папки', omitHint: 'Шаблоны через запятую (напр: .env,tests/)', contextPrompt: 'Контекст (необязательно)', contextHint: 'Дополнительный контекст для ИИ-агентов', execute: 'Запустить', skip: 'Пропустить', running: 'Выполняется...', analyzing: 'Анализ ошибок...', noCommand: 'Команда запуска не обнаружена', errorFound: 'Обнаружены ошибки', runBtn: '▶ Запустить', runningBtn: '⏳ Выполняется...', analyzeProject: '🔍 Анализ проекта', analyzingProject: 'Анализ...', lastRun: 'Последний запуск' },
  config: { title: 'Конфигурация проекта', created: 'Директория конфигурации создана', gitignoreUpdated: '.gitignore обновлён', configDir: 'Директория конфигурации', save: 'Сохранить изменения', confirmEdit: 'Подтвердить изменения' },
}
export default ru
